### ISSUE TITLE
Owlery does not like 'THAT' instead of AND in OWL Class Expressions

### ISSUE THREAD

**Issue by matentzn** [phenoscape/owlery#14]
The API fails hard if you replace AND with THAT ([example](http://owl.virtualflybrain.org/kbs/vfb/subclasses?object=%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00005106%3E+that+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002131%3E+some+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFFBbt_00003624%3E&direct=false)), producing the following output:

```
requirement failed: string matching regex `\z' expected but `t' found
``` 

Using THAT instead of AND is allowed in Protege. Perhaps owlery should support this as well?

**Comment by hlapp** [comment]
It actually seems that the [normative standard _requires_ ](https://www.w3.org/TR/owl2-manchester-syntax/#Descriptions) `that` instead of `and` in the position following the initial class IRI?

Seems like that's been relaxed in practice, but indeed not accepting `that` seems non-compliant with the standard.

**Comment by matentzn** [comment]
Wow, I would not go that far certainly... It is perfectly fine to use and IMHO. :) Thanks for flagging it a bug though, it would be great if we had that freedom.

**Comment by balhoff** [comment]
@hlapp I don't think `that` is required:

```
conjunction ::= classIRI 'that' [ 'not' ] restriction { 'and' [ 'not' ] restriction }
         | primary 'and' primary { 'and' primary }
         | primary
```

See the bar? The second alternative allows `and` there. I do agree the parser should support it. Owlet currently includes its own (incomplete) Manchester syntax parser, because the one in OWL API has some flaws which require declarations for the types of various terms.

**Comment by hlapp** [comment]
I see, so `primary` can be  a `classIRI` as well. I'm relieved 😌

We're still out of compliance though if we refuse `that` where the standard allows it.

**Comment by balhoff** [comment]
Vague memories of frustration with this parser generator DSL:

https://github.com/phenoscape/owlet/blob/3be2a68d30a9ab70d2f362b96dae1f6386f3be07/src/main/scala/org/phenoscape/owlet/ManchesterSyntaxClassExpressionParser.scala#L124

**Comment by balhoff** [comment]
I updated the parser in owlet and updated the dependency here. It sticks to the spec, so the only expression that can follow a `that` are a series of (possibly negated) restrictions.

By the way, there is other stuff missing from the parser, like pretty much anything "data".

**Comment by matentzn** [comment]
I strongly advocate a fully generic solution, but maybe we can keep the implementation low priority. I will open new issue.
